variable "avail_domain_name" {}
variable "compartment_id" {}
variable "VCN-DisplayName" {}
variable "image_ocid" {}
variable "subnet_ocid" {}
variable "InstanceShape" {}
variable "ssh_public_key" {}
variable "BootStrapFile" {}
variable "BootStrapFile1" {}
variable "ssh_private_key" {}
variable "mariadbvm_public_ip" {}
variable "uniqueid" {}