variable "compartment_ocid" {}
variable "prefix" {}
variable "image_ocid" {}
variable "instanceShape" {}
variable "subnet1_ocid" {}
variable "bootStrapFileDir" {}
variable "ad_name" {}
variable "sshPublicKey" {}
variable "ssh_private_key" {}
variable "admin_username" {}
variable "admin_password" {}
variable "linux_public_ip" {}