variable "compartment_id" {}
variable "DisplayName" {}
variable "vcn_ocid" {}
variable "security_list_ocid" {}
variable "route_table_ocid" {}
variable "internet_gateway_ocid" {}
variable "dhcp_ocid" {}
variable "avial_domain_name" {}
variable "avial_domain_name2" {}
variable "uniqueid" {}
