variable "avial_domain_name" {}
variable "avial_domain_name2" {}
variable "compartment_id" {}
variable "DisplayName" {}
variable "image_ocid" {}
variable "wsimage_ocid" {}
variable "subnet_ocid" {}
variable "casubnet_ocid" {}
variable "InstanceShape" {}
variable "ssh_public_key" {}
variable "BootStrapFile" {}
variable "ssh_private_key" {}
variable "chefserver_public_ip" {}
variable "chefautomate_public_ip" {}
variable "uniqueid" {}
